---
Resources:
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: eu-west-a
      ImageId: ami-466768ac
      InstanceType: t2.micro
      SecurityGroups:
       - !Ref MySecurityGroup
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: This is a ssh open group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 192.168.0.1/16
      EnableDnsHostnames: True
      InstanceTenancy: Default
    DependsOn:
    - MyInstance
    - MySecurityGroup




