---
AWSTemplateFormatVersion: 2010-09-09
#This is the basic S3 bucket resource
Resources:
  TestS3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain # Must be parllel with properites and type, not really sure what is this used for ?
    Properties:
      BucketName: will-be-my-first-cf-s3-modified-version-control-withoutfile #Must be in lower case and no space and special char
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: TestKeyName
          Value: TestValue
        - Key: TestKeyName2
          Value: TestValue2

