---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Edit /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "ansible.xyzcorp.com 169.168.0.1"
    - name: Install elinks
      yum:
        name: elinks
        state: latest
    - name: Create a user for audit
      user:
        name: xyzcorp_audit
    - name: copy the file
      copy:
        src: /home/ansible/motd
        dest: /etc/
    - name: second copy
      copy:
        src: /home/ansible/issue
        dest: /etc/

- hosts: network
  become: yes
  gather_facts: yes
  tasks:
    - name: nmap-ncat
      yum:
        name: nmap-ncat
        state: latest
    - name: network user
      user:
        name: xyzcorp_network

- hosts: sysadmin
  become: yes
  gather_facts: yes
  tasks:
    - name: copy module
      copy:
        src: /home/ansible/scripts.tgz
        dest: /mnt/storage
