---
- hosts: BOTP
  remote_user: hcladmin
  become: yes
  tasks:
    - name: This is a copy command we are testing.
      copy:
        src: /etc/fstab
        dest: /etc/fstab_ansible
        backup: yes
        remote_src: yes
    - name: This is to comment the old /sapmedia file
      lineinfile: 
        path: /etc/fstab
        state: present
        regexp: "10.4.4.1:/ad"
        line: "#10.4.4.1:/ad        /sapmedia  nfs4    nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev,noresvport        0       0"

    - name: This is to comment the old /sapmedia
      lineinfile:
        path: /etc/fstab
        state: present
        regexp: "10.2.5.1:/sapmedia"
        line: "#10.2.0.2:/sapmedia        /sapmedia  nfs4    nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev,noresvport        0       0"
  
    - name: This is to add the new /sapmedia at the end of the Fstab
      lineinfile:
        path: /etc/fstab
        line: "10.2.6.1:/sapmedia 	  /sapmedia  nfs4    nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev,noresvport        0       0"
    
    - name: This is to mount the new /sapmedia into the systems
      shell: "{{item}}"
      with_items: 
        - fuser -km /sapmedia
        - umount /sapmedia
        - mount -t nfs4 10.2.6.1:/sapmedia /sapmedia
     ignore_errors: true 

