---
#This YAML file is to modify the user data in BOTP landscape. 
- hosts: server2
  remote_user: root
  become: yes
  gather_facts: yes
  vars: 
    user_password: "$6$ansible$IwSzE2RB6pzfc2byyIu48zaAvIvKcw9Y8bTsRaFkULlU0I5eV3w5zzGX5NfPSgO/lMmToxL/0YbaPaxUU9LaJ0"

  tasks:
    - name: Remove the user 'just'
      user:
        name: just
        state: absent
        remove: yes  # This is used to remove the home directory of the respective user

    - name: Add the new users who joined BOTP recently 
      user:
        name: "{{item}}"
        create_home: yes
        shell: /bin/bash
        local: no
        state: present
        update_password: on_create
        password: "{{user_password}}"
      with_items:
        - mic
        - khanna 
      register: user_creation
    - debug: 
        msg: "{{user_creation}}"
        
    - name: Giving sudo permissions
      lineinfile:
        path: "/etc/sudoers"
        regexp: "^just"
        state: absent
        line: "{{item}}"
      with_items:
          - mic	ALL=(ALL)	ALL
          - khanna	ALL=(ALL)	ALL   
        
    - name: This is to ask user to change the password at login
      shell: "{{item}}"
      with_items:
        - creates="/home/mic" chage -d 0 mic 
        - creates="/home/khanna" chage -d 0 khanna
      when: user_creation.changed == true
